Add exit handling to build system

diff --git a/scripts/build-functions b/scripts/build-functions
--- a/scripts/build-functions
+++ b/scripts/build-functions
@@ -49,8 +49,9 @@ COL_CLEAR=$'\e[0m'
 # Main function executed when this file is sourced.
 #
 build_functions_main() {
-    local start_time
-    start_time=$(date +%s)
+    trap _exit_handler EXIT
+
+    start_timer "PACKAGE_TIMER"
 
     # Identify and set the OS/ARCH/JOBS/PLATFORM variables.
     _identify_os_arch
@@ -60,6 +61,11 @@ build_functions_main() {
 
     print_debug "Debug enabled."
     print_debug "OS: ${OS} ARCH: ${ARCH} PLATFORM: ${PLATFORM}"
+
+    # Remove any existing build log.
+    if [[ -r "${BUILD_LOG}" ]]; then
+        rm -f "${BUILD_LOG}"
+    fi
 
     # Source the package variables.
     _unset_package_variables
@@ -104,18 +110,7 @@ build_functions_main() {
             ;;
     esac
 
-    local stop_time
-    stop_time=$(date +%s)
-
-    local str_time
-    str_time=$(pretty_time $((stop_time - start_time)))
-    if [[ -v VIRTUAL_PACKAGE ]]; then
-        print_ok "Virtual package elapsed time: $str_time"
-    else
-        print_ok "Package elapsed time: $str_time"
-    fi
-
-    print_debug "Reached end of script."
+    print_debug "Reached end of main function."
 }
 
 # --- Helper functions ---
@@ -229,6 +224,57 @@ wait_progress() {
     return $rc
 }
 
+
+# Start a timer.
+#
+# $1 - Name of timer.
+start_timer() {
+    local timer_name=$1
+
+    # Watch very carefully ... there is nothing up my sleeves ...
+    declare -g "$timer_name"="$(date +%s)"  # Start time in seconds since epoch
+    # Hey presto! We have declared a global variable from a function argument!
+}
+
+# Stop a timer.
+#
+# $1 - Name of timer.
+#
+# Outputs the elapsed seconds since the start of the timer.
+stop_timer() {
+    local timer_name=$1
+
+    # This is where we put the rabbit back into the hat ...
+    local start_time=${!timer_name}
+
+    local stop_time
+    stop_time=$(date +%s)
+
+    echo $((stop_time - start_time))
+}
+
+# Stop a timer, and print an 'ok' message.
+#
+# $1 - Name of timer.
+# $2 - Message to print. The formatted time will be appended.
+stop_timer_ok() {
+    local str_time
+    str_time=$(pretty_time "$(stop_timer "$1")")
+
+    print_ok "${2} ${str_time}"
+}
+
+# Stop a timer, and print an 'error' message.
+#
+# $1 - Name of timer.
+# $2 - Message to print. The formatted time will be appended.
+stop_timer_error() {
+    local str_time
+    str_time=$(pretty_time "$(stop_timer "$1")")
+
+    print_error "${2} ${str_time}"
+}
+
 # --- "builtin" functions ---
 
 # Fetch source package.
@@ -305,14 +351,10 @@ builtin_unpack() {
 #
 # This is not expected to be called except for virtual packages, as we don't
 # know how to build any package ourselves.
-#
-# Sets global variables:
-#   VIRTUAL_PACKAGE         - only defined if we are a virtual package.
 builtin_build() {
     if [[ -v BUILTIN_FETCH_NONE ]] && [[ -v BUILTIN_UNPACK_NONE ]]; then
         # and since the user did not define a build() function, then this is a
         # special case, this is a virtual package.
-        VIRTUAL_PACKAGE=1
         print_debug "builtin_build(): determined we are a virtual package."
     fi
 }
@@ -330,7 +372,7 @@ builtin_clean_source() {
     fi
     print_ok "Cleaning package source."
     rm -rf "${PACKAGE_SOURCE_DIR}"
-    rm -rf "${BUILD_LOG}"
+    rm -f "${BUILD_LOG}"
 
     return 0
 }
@@ -456,6 +498,39 @@ builtin_deps_clean_all() {
 
 # --- Internal functions ---
 
+# We have caught exit, if it was an error, then print a message to the
+# log file.
+_exit_handler() {
+    local exit_code=$?
+
+    if [[ $exit_code -eq 255 ]]; then
+        # Special exit code for dependencies that skip themselves.
+        # Do nothing, say nothing, exit successfully.
+        print_debug "_exit_handler(): exit code 255, skipping."
+    elif [[ $exit_code -ne 0 ]]; then
+        # Non-zero exit code.
+        stop_timer_error "PACKAGE_TIMER" "Package elapsed time until error:"
+        if [[ -v BUILD_LOG ]] && [[ -r "${BUILD_LOG}" ]]; then
+            # See if there's a non-empty build log for the user.
+            local build_log_size
+            build_log_size=$(wc -c < "${BUILD_LOG}")
+            if [[ $build_log_size -gt 0 ]]; then
+                print_error "See build log for errors: ${BUILD_LOG}"
+            fi
+        fi
+    else
+        if [[ -v HAVE_PRINTED_TITLE ]]; then
+            # Only print the elapsed time if we have printed any output
+            # to the user before exiting.
+            stop_timer_ok "PACKAGE_TIMER" "Package elapsed time:"
+        fi
+    fi
+
+    print_debug "Reached end of exit handler with exit code: ${exit_code}"
+
+    exit $exit_code
+}
+
 # Ensure we have not already been visited as part of a dependency chain.
 # This is used to prevent infinite loops.
 _ensure_not_visited() {
@@ -471,7 +546,7 @@ _ensure_not_visited() {
             fi
             if [[ "${visited}" == "${PACKAGE_NAME}" ]]; then
                 print_debug "_ensure_not_visited(): We were already visited, exiting early."
-                exit 0  # Nothing further to do, return success.
+                exit 255  # Nothing further to do, return special code.
             fi
         done
     fi
@@ -494,6 +569,7 @@ _call_dependencies() {
     # Find each dependency and call their build.sh script
     local dependency
     local dep_result
+    declare -a dep_ok
     for dependency in "${DEPENDENCIES[@]}"; do
         if [[ -z "${dependency}" ]]; then
             continue
@@ -505,10 +581,27 @@ _call_dependencies() {
         print_debug "_call_dependencies(): Calling: \"$dependency/build.sh\" $1"
         ../"${dependency}/build.sh" "$1"
         dep_result=$?
-        if [[ $dep_result -ne 0 ]]; then
+        if [[ dep_result -eq 255 ]]; then
+            # Dependency skipped itself, do nothing
+            print_debug "_call_dependencies(): Dependency skipped itself, doing nothing."
+            continue
+        elif [[ $dep_result -ne 0 ]]; then
+            # We are going to exit here, but we want to list the successsful
+            # dependencies first.
+            local i
+            for i in "${dep_ok[@]}"; do
+                print_ok "Completed dependency: $i"
+            done
             print_error "Failed to build dependency: $dependency"
             exit 1
         fi
+        dep_ok+=("$dependency")
+    done
+
+    # If we got this far, then all dependencies performed action successfully.
+    local i
+    for i in "${dep_ok[@]}"; do
+        print_ok "Completed dependency: $i"
     done
 }
 
